### ISSUE TITLE
UASB: What we have been doing and what we will be doing

### ISSUE THREAD

**Issue by cjmsmith** [AguaClara/UASB#108]
For the past few weeks, the UASB has been carefully planning our semester ahead of us. We have been completing several required trainings, becoming more familiar with software frequently used in AguaClara, and most importantly, finalizing our designs for our UASB reactor so we can start building it at the Ithaca Area Wastewater Plant! We have met with Monroe to discuss our design and completed literature reviews to obtain a better idea of what would and wouldn't system. The next few weeks, we will be running testing; Ananya and Nina will preform tests on our model, using tapioca to model the sludge blanket, while Ian and Cara will be working on the design aspect of the system. All in all, we are excited for what the future holds and can't wait to start building!

**Comment by IanCullings** [comment]
Hey @cjmsmith , sorry I forgot to mention this but the discussions should be posted on this page: [UASB Team](https://github.com/orgs/AguaClara/teams/uasb) I copied this one there. Also just a reminder to write this weeks check, ideally by the end of the day today.

**Comment by cjmsmith** [comment]
Sorry about that! Writing check now
@IanCullings
