### ISSUE TITLE
EPA credit for funding

### ISSUE THREAD

**Issue by monroews** [AguaClara/UASB#110]
The following statement must be included in reports that your teams generate. Please go back and add the first acknowledgement into any reports published 

between 1/1/18 and January 1, 2019
This publication [article] was developed under Assistance Agreement No. SU-83926801 awarded by the U.S. Environmental Protection Agency to Cornell University.  It has not been formally reviewed by EPA.  The views expressed in this document are solely those of [name of recipient or names of authors] and do not necessarily reflect those of the Agency.  EPA does not endorse any products or commercial services mentioned in this publication.

after January 1, 2019
This publication [article] was developed under Assistance Agreement No.SU-83948601-0 awarded by the U.S. Environmental Protection Agency to Cornell University.  It has not been formally reviewed by EPA.  The views expressed in this document are solely those of [name of recipient or names of authors] and do not necessarily reflect those of the Agency.  EPA does not endorse any products or commercial services mentioned in this publication.

**Comment by IanCullings** [comment]
Done!  I made a note in the reports folder for future reports to include this.
