### ISSUE TITLE
Consider bench-top tests for UASB flow control questions

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/UASB#13]
Are there any bench-top tests that we can do to test spread of flow for UASBs? 

ex: The textbook reported an influence area of 2-3 m^2 for each influent port, but is that true? Can we test that by using tracers to figure out how long it takes flow to spread over that area (if it spreads that far at all?) How does sludge vs granular bed composition impact the spread? If there are multiple ports but then they get clogged so that only one works, does it mean that the high flow through the single working port will make a preferential flow "hole" through the bed? 

Trickling filter team is starting to do some work to test flow distribution parameters. We can talk to them to figure out if there could be an analogous experiment for us. 

This type of bench-top testing will be helpful before we do a full reactor fabrication, but we should still have some python code written to document the design for influent ports. The area of influence (which we want to confirm from both literature and possible experiments) can be a variable input into the code that calculates the number of influent ports required for a specific reactor size. 

Let's talk more about this on Friday - I just wanted to bring it up here so we could all start thinking about it.

**Comment by IanCullings** [comment]
See #65
