### ISSUE TITLE
Altered Biogas Lid/Storage

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#15]
I created a markdown file with new calculations on volumetric biogas production based on equations from the textbook and documentation on the altered idea/concept on the lid.  

@zam7 can you take a look at the file?  I'm going back and forth between a floating gas holder vs a fixed gas holder like the ones shown here: http://www.susana.org/_resources/documents/default/2-1799-biogasplants.pdf 

Alternatively we could also have a separate tank of water that biogas can be directed into.

**Comment by zacchen15** [comment]
This should also help: 
http://www.suscon.org/pdfs/news/biomethane_report/Chapter_4.pdf

**Comment by zacchen15** [comment]
| Type of Storage | Pros | Cons|
|:----------------|:----------|:----------|
| Gas Bag | (1) flexible and easy connection on top of next to reactor **(2) Cheap and cost effective** (3) Easy to transport for reactor to kitchen use| (1) Fragility and Leakage (2) Replace frequently - can these materials be found locally? |
| Fixed Lid | (1) durability (2) no concerns about movement (3) can use prefab barrel | (1) we could need to catch water displaced from reactor in effluent and have storage so that it may return upon offgassing |
| Floating Lid | (1) no problem displacing water (2) same concept as fixed lid | (1) will it float or are we just displacing water again? |

**Comment by zacchen15** [comment]
Meeting with Zoe: 3/9

EXECUTIVE DECISION: SYSTEM DESIGNED AROUND THE GAS BAG 
- Good for multi-person use
- fixed removable lid that can be connected to bag so we can collect or flare directly

**Comment by zacchen15** [comment]
https://web.wpi.edu/Pubs/E-project/Available/E-project-101614-131013/unrestricted/Biogas_Capture_System_for_Urban_Farms.pdf

**Comment by zacchen15** [comment]
- Read through the susana stuff to get a better idea of how gas flows from the reactor will work 
- Discuss with Zoe tomorrow, if these is still an impasse, talk to Monroe about if this will work

**Comment by IanCullings** [comment]
Notes from 3/23/18 Meeting:

Design notes:
- Finish Biogas code
- Determine volume of the attached system and lid system
- Research/shop for gas bags and look at sizing
- Determine maximum time needed before failure
- Determine critical pressure and compare to the current pressure system
- BASED ON SIZE OF GAS BAG

Fabrication notes:
- Cap-like lid is much harder to fabricate than flat lid
- How to fabricate gas-tight system?
-Using bag as inner lining to gas cap???

**Comment by zacchen15** [comment]
Added the calculations to "Biogas Storage" file in repo

The function takes (1) daily production rate (2) desired maximum amount of storage (3) maximum time before failure (4) diameter of the lid 

and calculates (1) the time until failure if the temporary storage is full (2) the height of the lid given the diameter of the lid

Note: I just used diameter because I wanted to have a general shape for the lid.  This can be changed if we have a square lid or something.

**Comment by IanCullings** [comment]
Code is finished and in design manual
