### ISSUE TITLE
Report Writing (Due 3/9)

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#16]
- Copy the template from the resource repo to the UASB repo for work
- Ask @zam7 what we should take out and what we should add to the report and how we can include our code
- Should grant writing progress go in the report?

**Comment by ananya-gangadhar** [comment]
@JenniferKJackson and I started on the Introduction and Abstract sections of the report. We're putting the text on a Google doc (link below) because Markdown is mean and scary

[https://docs.google.com/document/d/1dV8maX-a1ceZiQ1Ze2UO264O8TdDyDwZf0pOnsPgg8w/edit](url) @zacchen15 @icullings @zam7

**Comment by zam7** [comment]
[does this work?](https://docs.google.com/document/d/1dV8maX-a1ceZiQ1Ze2UO264O8TdDyDwZf0pOnsPgg8w/edit)

**Comment by zacchen15** [comment]
Intro 
- briefly describe the work that will be done this semester
Lit Review
- Review some of the old reports and copy those
- add the literature on inflow pipes (textbook and any new stuff that we've found)
Methods
- Take this out
- Detail in words the design process and the design algorithm 
Result
- copy and paste the code into the results section
Analysis
- just talk about the overall results from the design calculations (ie not much biogas produced)
Bib
- Normal text form for the references

**Comment by zacchen15** [comment]
We'll sort out the details of this tomorrow when we meet as a full team

**Comment by zacchen15** [comment]
I've added a little template to the report on how the formatting should look and moved some of the intro/lit review that seem relevant from previous reports.

@ananya-gangadhar @JenniferKJackson can you guys add the table for your design parameters and include a small blurb following the rest of the template?  Also add some of the literature to the "Problems Associated with UASBs" section under the lit review.

@IanCullings I moved over the size and biogas calculations can you move the tube settler document from Jupyter to the Manual markdown?
