### ISSUE TITLE
Please Change Your Usernames to Your Actual Names

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#18]
Go to "Settings" from your profile drop down:
![image](https://user-images.githubusercontent.com/32373771/36993295-72bc55f0-207b-11e8-8c01-a7ce73d1ffbb.png)

Click on "Account":
![image](https://user-images.githubusercontent.com/32373771/36993371-a036d992-207b-11e8-8bb5-9923053c4387.png)

Scroll down to "Change Username":
![image](https://user-images.githubusercontent.com/32373771/36993483-f58ef686-207b-11e8-891f-cc666353f7ec.png)

**Comment by ananya-gangadhar** [comment]
Done updating profile!

**Comment by JenniferKJackson** [comment]
Done! Thanks for the instructions!

**Comment by IanCullings** [comment]
Done, thanks for the reminder!
