### ISSUE TITLE
Symposium Presentation 

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#21]
- create doodle poll to meet over weekend
- get team dinner on Friday after the meetings to talk about this stuff?
- meet over weekend to practice the presentation before Monday

**Comment by IanCullings** [comment]
Also @JenniferKJackson @ananya-gangadhar I assigned slides to everyone in the speaker notes.  If you could look at your slides and make sure you're comfortable with them.  If you have any questions on what to say or want to switch with someone just let us know.

**Comment by JenniferKJackson** [comment]
Sounds good.  We figured out what we want to present on, and we're going to finalize the speaker notes and add pictures tomorrow!

**Comment by ananya-gangadhar** [comment]
@JenniferKJackson @zacchen15 @IanCullings I made the slides for influent flow. We just need to add more speaker notes and decide who says what between Jennifer and I.
