### ISSUE TITLE
Meeting with Ed + Ruth, 4/11

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#25]
Hi all, just making this as an Agenda so we can begin compiling questions/talking points

4/11, 3pm, Hollister 208

Questions for Ed:
- Average BOD concentration in influent line.  How variable?
- Construction/transportation of UASB to IAWWTF
-How flaring system works

**Comment by zacchen15** [comment]
Before this, we need to determine a way to removal FOG

**Comment by IanCullings** [comment]
Meeting finished, agenda and notes here: https://www.google.com/url?hl=en&q=https://docs.google.com/document/d/1NEuNgkB6boj0fLLTKkNQrwYFikOS5jMa_elYHATtSy0/edit?usp%3Dsharing&source=gmail&ust=1524072278830000&usg=AFQjCNGCZkCNNFYTfEhn08DEDi9alouMtQ
