### ISSUE TITLE
Meeting 3/21

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#29]
- What are the needs of the influent piping?
- Who will be doing the Fusion?  Let's plan a meeting with Matt with whomever would want to be involved 
- What exactly do we want from him
- Ask for resumes for EPA P3

**Comment by JenniferKJackson** [comment]
Ask Zoe on Friday: Does influent need to come straight down (& hit the V head on), or can it hit the V at an an angle?

**Comment by zacchen15** [comment]
Notes on Influent:
- Influent lines for domestic WW usually come form the top to prevent clogging of solid matter in the pipes
- Best to keep out sharp turns in the line 
- Angled entrance hard to fabricate but we also don't want a 90 degree turn 
- at least 50 cm of head required required

Notes on Biogas Storage:
- We want open most open space possible on top to allow passive collection of biogas 
- Could a sealant for any hole drilled be useful?

On Resumes:
https://drive.google.com/open?id=1gUseJ9KbVL_VLZMSBsFwPwor1u1eEG0r

**Comment by zacchen15** [comment]
Check Van Lier for scum removal
