### ISSUE TITLE
3/23 Meeting with Zoe 

### ISSUE THREAD

**Issue by ananya-gangadhar** [AguaClara/UASB#32]
**Flexible tubing for influent pipes**
Is it a feasible material for wastewater? Clip-on to bottom or make apertures?

**How to achieve necessary exit velocity for small-scale flow**
Talk to Prof. Richardson about balancing clogging issues in small pipes with necessary exit velocity.
Recommended bottom-end pipe diameter around 50mm. Recommended pipe diameter 75-100mm. Both based on practical experience. 
*Note: Most UASB reactors don't have constant flow rates so they HAVE worked in periods of low flow.*

****
@zoemaisel @JenniferKJackson @zacchen15 @IanCullings

**Comment by JenniferKJackson** [comment]
![image](https://user-images.githubusercontent.com/31327430/37852508-36fc3584-2eb9-11e8-8de2-abf52779b471.png)

**Comment by JenniferKJackson** [comment]
![img_5824](https://user-images.githubusercontent.com/31327430/37852689-e7345dc8-2eb9-11e8-9163-a22b448797bf.jpg)

Sketch of flexible inlet piping.  Would need rigid fastenings for when flexible tubing enters the reactor at an angle.  Also needs a fastening at the bottom to make sure WW exits the pipe going directly down.

**Comment by JenniferKJackson** [comment]
For this week: Figure out flow splitter

**Comment by zacchen15** [comment]
I found a cool looking thing here: https://ocw.tudelft.nl/wp-content/uploads/12._Anaerobic_Sewage_Treatment.pdf

on slide 11 it looks a lot like what we're trying to accomplish
