### ISSUE TITLE
Research Report 2 Due - 4/20

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#35]
Second draft of the research report due. 
- Address all of Natalie's comment
- Add Figures and more clear captions for each of the figures
- Add doc tests to the code
- Update the code for biogas

**Comment by JenniferKJackson** [comment]
- Add influent pipe code

**Comment by zacchen15** [comment]
- Clean up the tables so add specific references
- Update the bibliography (Let's use Zotero to make things easier) 
- Add figures to the parts of the Manual that seem to need more specificity/visual aid

**Comment by zacchen15** [comment]
Please edit the sections what you wrote according to the comments given by Natalie

Abstract

Intro and Lit Review 
- @JenniferKJackson @ananya-gangadhar Can you help out here?  I know you didn't write these sections but it would be valuable to go through these sections for background.  I will also be going through this section at the end.  

UASB Size
- @zacchen15 will make diagrams for this @IanCullings 

Biogas 
- @zacchen15

Influent Distribution
- @JenniferKJackson @ananya-gangadhar 

Tube Settler 
- @zacchen15 

FOG
- @IanCullings 

Sludge Weir
- @IanCullings 

Future Work 
- @IanCullings 

Bibliography
- Please send all links to papers used to @zacchen15.  I can put it all in Zotero and import it easily

**Comment by IanCullings** [comment]
Submitted, awaiting comments
