### ISSUE TITLE
Atom Question

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#39]
@zoemaisel is there any easy way to copy the output of a function from the little text box?  I'm trying to add doctests without having to rewrite the entire output.

**Comment by zoemaisel** [comment]
![screen shot 2018-03-27 at 8 17 46 pm](https://user-images.githubusercontent.com/31140352/38001665-ff7662b0-31fb-11e8-8f16-dff9bdc52aae.png)
 

When I hover over the output from a print statement, it gives me the option that if I click it, it automatically copies it. Does this happen for you?

**Comment by zacchen15** [comment]
![image](https://user-images.githubusercontent.com/32373771/38002349-b5362d44-31ff-11e8-9436-fc981ae70656.png)

I don't think I can do that.  When I try, it copies the line of code that the cursor is on rather than the print statement output

**Comment by zacchen15** [comment]
Atom is weird on my computer but I figured it out.  Thank you!
