### ISSUE TITLE
To-do list by 3/29

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#40]
Grant:
- Outline parts of the Phase II proposal

Biogas: 
- Clean up the biogas code 
- Determine final volume and get finalized dimensions
- add documentation

**Comment by IanCullings** [comment]
Some talking points for Thursday:
- 3 ml/s term: revisit? Seems much too large 
- Finalize FOG plan for presenting to Ed after break
- Any preparation for EPA conference?
