### ISSUE TITLE
Proposal To-Do List 4-26-18

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#47]
PROPOSAL DRAFT DUE MAY 4th
- Paragraph on team structure on project schedule ZAC
- FOG removal IAN
- Hydrogen Sulfide scrubbing 
- Overall sustainability ZAC and IAN
^ These parts done by Thursday May 3rd

- Quality Insurance (short)
- BUDGET
- Budget justification
- References

Other details
- Standard Form
- Key contacts
- Table of Contents
- Human subjects
- Relevance to EPA 
- Current and pending support form
- Resumes

**Comment by JenniferKJackson** [comment]
Hi - what can Ananya and I help with?? @IanCullings @zacchen15
