### ISSUE TITLE
Draft letter request to APP Honduras

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#5]

**Comment by icullings** [comment]
@zam7 Questions for review:
-Should we include a draft letter of support for IAWWTF?
-Is it worth reaching out to Aguaclara LLC for a support letter? (I checked and the letters don't contribute to the 15-page limit)
-Should Ed be our contact for the letter, or do we need to get someone in a higher position?
-Should I refer to Monroe as Monroe or Dr. Weber-Shirk?

**Comment by icullings** [comment]
Email is ready to be sent once executive summary is complete

**Comment by zam7** [comment]
Refer to Monroe as Monroe for the APP letters but as Dr. Monroe Weber-Shirk in any example letter that will be used in the EPA proposal or to IAWWTF

**Comment by IanCullings** [comment]
The letter is complete, will be sent once Executive Summary is ready.

**Comment by IanCullings** [comment]
Received! 4/25
