### ISSUE TITLE
Meeting with Ruth 5/9

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#55]
Agenda:
- Reminder for final sympoisums 
- Better synthetic wastewater stock: with particulates
- Grant writing is done! (we are waiting on comments and will edit accordingly
- Budget items coming up and other forms that we need to collect

**Comment by JenniferKJackson** [comment]
Wastewater "recipe": https://www.researchgate.net/post/How_do_we_prepare_lab_synthetic_wastewater_in_developing_countries

**Comment by zacchen15** [comment]
- ground up dog food can be used as stimulant for solids in WW 
- we could check out a recipe that includes inorganic matter such as wood or sand as well 
- note that we also want to avoid settle-able materials
- we could potentially get away with just using water, sand, and food starch
