### ISSUE TITLE
Draft Letter request to IAWWTF

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#6]

**Comment by zam7** [comment]
Send IAWWTF an example letter of support that is specific to the things we will gain from working with them (physical reactor space, access to WW, sampling and testing capability in their lab space)

**Comment by zam7** [comment]
Send the email to Ed Gottlieb <egottlieb@cityofithaca.org> and Jose Lozano <jll13@cornell.edu> , and copy Prof. Richardson

**Comment by icullings** [comment]
@zam7 email and draft letter are complete, please review when you have the chance.
Questions:
-Is the draft letter too short?  I wasn't sure what else to include and didn't want to write just to fill space
-Should I include any other details about the means of support?

**Comment by zam7** [comment]
Added more comments! I don't think that the draft letter is too short Looks good.

We should also copy Monroe.

**Comment by IanCullings** [comment]
The letter is complete, will be sent once Executive Summary is ready.

**Comment by IanCullings** [comment]
Received 5/3!
