### ISSUE TITLE
Hydraulic Code

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#64]
Write Hydraulic Code for Influent system, and use to check variable parameters.

@ananya-gangadhar write similar code in excel to check and keep Ruth in the loop?

**Comment by ananya-gangadhar** [comment]
Will do! I'm hoping to see what basic formulae we use on Tuesday so I can plug those into Excel and crunch those numbers!

**Comment by IanCullings** [comment]
Add hydraulic code to determine new geometry with new design.  Ensure that geometry leads to lower descending sewage velocity (< 0.2 m/s), while still giving the required hydraulic head necessary (~25 cm).  May run into problems between two constraints.  Image of system below:

![img_1216](https://user-images.githubusercontent.com/19654169/41797699-0eba0fd4-7639-11e8-8d43-0f88ab8d6c2c.jpg)

**Comment by IanCullings** [comment]
Figure out how to import functions from earlier in document to later functions.

**Comment by IanCullings** [comment]
Functions are written: they just need to be tested more and implemented in the design section
