### ISSUE TITLE
Research more on biogas collection

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#7]
- Look at design manual (the text)
- Talk to people in Carpenter to see irl designs and specifications

**Comment by icullings** [comment]
Looking for simplest way to capture, transport and store (plus use!) biogas

**Comment by ananya-gangadhar** [comment]
I found a bunch of links about biogas production in UASB reactors at the bottom of this article:
https://www.sciencedirect.com/science/article/pii/S0960852415000218
Don't know how useful it might be, but thought you might be interested.

**Comment by zacchen15** [comment]
Goals (by next week): 
- Update the designs to reflect our ideas about the system 
- Edit the calculations to reflect the equations in the textbook

**Comment by zacchen15** [comment]
Design Considerations:
- Double barrel design
- Create calculations and sizing of the apparatus
- Create new .md file for this work
- Base calculations off of biogas calculations from last semester

**Comment by zacchen15** [comment]
Created the .md file in accordance to this
