### ISSUE TITLE
Fabrication Manual

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#71]
Create manual documenting fabrication plans for each section of the reactor.  For each component, this should include:

* Design parameters and code
* Justifications for design
* Any uncertainties
* Fabrication techniques necessary to build 
* When built, photos and documentation on the process

Manual should also include links to and photos of the fusion model.

**Comment by ananya-gangadhar** [comment]
I've updated the fabrication manual to the best of my knowledge. Can either of you give it a quick read and let me know if any of the descriptions are too vague or incorrect?

@IanCullings @isakaminsky

**Comment by IanCullings** [comment]
Fabrication manual model created, will be updated as we continue to build full reactor!
