### ISSUE TITLE
Summer Research Report 1

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#76]
Hey @juanchon998, [here](https://github.com/AguaClara/UASB/blob/master/summer2018report.md) is our first research report.  Thanks for reading it over!

**Comment by juanchon998** [comment]
Hey UASB team, I have graded/edited your research report. However, I cannot push my changes to master, apparently I don't have permission to access this repository. Could someone please grant me permission? I would much appreciate it! @IanCullings @isakaminsky @ananya-gangadhar 

![image](https://user-images.githubusercontent.com/27255695/42189920-837661c8-7e28-11e8-95a3-306ebe73ae2b.png)

**Comment by isakaminsky** [comment]
okay i think i did it

**Comment by IanCullings** [comment]
Not sure if you did Isa but I definitely got it now

**Comment by isakaminsky** [comment]
i made him a collaborator
