### ISSUE TITLE
Draft Stove Information Letter to Honduras

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#8]
- Research basic stove/usage methods
- Draft email and run by Zoe

**Comment by icullings** [comment]
Include:
-Basic resources on biogas usage
-Schematics for stoves or designs 
-One of two recommendations for use

**Comment by zam7** [comment]
Original email from Ruth: 

Marjorie
Thank you so much for the pictures and for showing me around the Tatumbla treatment plant. 
I believe that the system could be a point of collaboration with the aguaclara wastewater team. 
I'm ccing the student leader of that team and Monroe
I'm interested in a couple of followup questions:
1 are there any diagrams or other sketches of the system?
2. You mentioned wanting to get Luzwin and the other operator a cook stove. As I said there are cool stoves that can run on biogas from a UASB. do you know how much biogas you get? I'm certain that 70-households worth of wastewater will provide more than enough biogas for their cooking needs. We could get you specifics on stoves to look into
I left Erikas team with equipment to process more samples for PathogenPanel analysis and hope we can discuss followup samples to collect and test 
Regards

**Comment by zam7** [comment]
[Cornell Mail - Re_ Tatumbla photos.pdf](https://github.com/AguaClara/UASB/files/1764330/Cornell.Mail.-.Re_.Tatumbla.photos.pdf)

**Comment by zam7** [comment]
A [resource](https://energypedia.info/wiki/Biogas_Appliances) that Ruth sent Marjorie.

These are the only three correspondences that I was copied on.

**Comment by IanCullings** [comment]
@zam7 I wrote up a draft in google drive with some information and shared with Dr. Richardson for discussion tomorrow.  Feel free to take a look if you have the time. I'm a little confused on what recommendations we should make, just since we don't have much direct experience with the system yet.

**Comment by zam7** [comment]
@IanCullings Can you hyperlink document that you're drafting in directly here? I don't think I see it on the drive.

**Comment by IanCullings** [comment]
@zam7 https://docs.google.com/document/d/1xWJCiXrk2K8T4Qqnau45R8mPrWZb4xvTZNJgfo6U8f8/edit?usp=sharing

**Comment by zam7** [comment]
@IanCullings looks good to me! Just add a link that goes directly to a page that has specific models available for purchase so they can also look at those options. Lmk if you have trouble finding a suitable link.

**Comment by IanCullings** [comment]
@zam7 I haven't been able to find stoves for sale that use biogas specifically.  Do you know of any resources?  I could also recommend an LPG stove and detail how to convert it to biogas

**Comment by zam7** [comment]
Ok, I also see mostly LPG stoves. Let's send them a link to LPG stoves that they can buy and then convert to biogas

**Comment by IanCullings** [comment]
Email Sent 3/12
