### ISSUE TITLE
Task List Record

### ISSUE THREAD

**Issue by ananya-gangadhar** [AguaClara/UASB#84]
Hello all,
Since it is really difficult schedule-wise to have all the UASB members working together for more than a couple hours a week, I thought it might be useful to have a record of what each person works on each day. This is to allow other members to stay updated on the progress the subteam is making.

I've created a Google doc in the UASB Google Drive([this](https://docs.google.com/document/d/1TxvZaoMEvs2OfK5-8Hd3IBb6M1MQzfmpi_6uIvvbsVc/edit) is the link) with a table that each member can fill in, and have created a few entries to provide a template. Please try to fill these in as regularly as possible. It'll be a huge help for members who aren't here all week!
@IanCullings @isakaminsky @AlyciaStorch

**Comment by IanCullings** [comment]
While I like the idea I don't really think it's worth it at this point in the summer!  We should consider using a similar system in the Fall semester if we split into teams again.
