### ISSUE TITLE
Research Report Due 7/27

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#85]
The second draft of our research report is due this Friday.  I've assigned tasks out below, let me know if you have questions/comments/concerns.

@ananya-gangadhar can you finish addressing Juan's comments and remove the actual comments once you are done?  Also please add a introduction/motivation section citing the report you mentioned about UASB efficiency in India.  Finally, if you have extra time if you could try and figure out why our images won't display in atom?

@isakaminsky can you add add to the documentation I wrote for the tapioca tests, and fill in our observations as we continue the tests this week?  Also please add your data from the tipping bucket tests and detail the next steps.

@AlyciaStorch if you have time while working on the fusion modeling of the UASB, could you look into making a nice rendered model of the components and eventually the entire the system?  Having a digital model [similar to this model of the 1 LPS](https://myhub.autodesk360.com/ue28a131e/g/shares/SH7f1edQT22b515c761e7fb9f856bcad56c1) would be awesome as well.

I'll work on the biogas (both description and code) and make graphics for that, and continue editing the full document.  

@juanchon998 do you mind reading our report once we're done and offering more comments?  I can make you baked goods as thanks :)

**Comment by juanchon998** [comment]
I will read it and grade/review it once you're done! Just give me a shout-out on this issue once it's ready and I'll look it over

**Comment by ananya-gangadhar** [comment]
@IanCullings I was thinking of leaving the comments in the doc so that @juanchon998 can see that the issues have been worked on and can avoid repetitions.

**Comment by IanCullings** [comment]
@ananya-gangadhar that's totally fine.

**Comment by IanCullings** [comment]
One more task that needs to be done is to create design drawings of the discarded tipping bucket designs.  These could be in fusion, google drawings, or just hand drawn.
