### ISSUE TITLE
NEGSWS Presentation

### ISSUE THREAD

**Issue by ananya-gangadhar** [AguaClara/UASB#96]
I'm hoping to keep track of the developments regarding the logistics of the Graduate Water Symposium on this issue. As of now, I believe we ought to schedule a meeting with Monroe and Will. Thoughts, @IanCullings?

**Comment by IanCullings** [comment]
The poster is complete and in the newly created [Posters and Presenations](https://github.com/AguaClara/UASB/tree/master/Posters%20and%20Presentations) folder in our Repo!
